### ISSUE TITLE
integration with `SDMLayers`

### ISSUE THREAD

**Issue by gottacatchenall** [EcoJulia/BiodiversityObservationNetworks.jl#6]
Needs an implementation of `rand` or `_generate` that handles `SDMLayers` as inputs, in particular, handling of `nothing` values

**Comment by tpoisot** [comment]
`SimpeSDMLayer`s are iterable, if that helps.

We can restrict to those with a `Number` inner type, then replace the `nothing` by `zero(T)`, and badbing badaboom or whatever

**Comment by gottacatchenall** [comment]
this was done in #16
