### ISSUE TITLE
API change(ish)?

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/BiodiversityObservationNetworks.jl#7]
@gottacatchenall what is your input on the following additional way to use the package: `rand(method, landscape, coordinates)`?

Hear me out: what if we want to get 1000 points using a first method, and then 100 using a second method. Something like:

~~~julia
landscape |> rand(method1) |> rand(method2)
~~~

would be very cool to write, right? As far as I can tell the only change required would be to make sure that the methods return `(landscape, coordinates)`, and maybe an additional method so that `rand(method)` is a function that unpack its arguments?

This would deviate from what `rand` does, so we may want to think about a rename? `monitoringsites`?

**Comment by gottacatchenall** [comment]
Yeah that looks good, in conversations with BiaB block 3 team we've also formulated this type of structure for the flow of info, I think it'll look something like

(1) Input `Layers`: a set of `N_L` raster layers we want to optimize against
(2) `Weights`:  A (`N_L` by `N_S`) matrix that we use to aggregate the input layers into scores
(3) `Scores`: a set of `N_S` scores to be considered as the trade-off axes for optimization (detecting true current state vs. detecting temporal change, in our case) 
(4) `MonitoringSites`: a resulting set of points from `monitoringsites`
(5) `PriorityMap`: a raster of the priority of each cell in the rasters for monitoring

And the syntax from beginning to end would look like 
```
layers = Layers(landcover, sdmuncertainty, climatevelocity)
filter = layers |> monitoringsites(BalancedAcceptance(500)) |> monitoringsites(AdapativeSpatialSampling(50))

examplepoints = monitoringsites(filter)
tradeoffcurve = validate(examplepoints, process)
```

where the resulting tradeoffcurve is to be used for validation, something like 
![concept_working_group (copy)](https://user-images.githubusercontent.com/17133743/161607954-51c566b6-110a-4609-8bb0-67af802e6291.png)

and `process` is _eventually_ a simulation model based around MetacommunityDynamics.jl, but for now a method of drawing occurrence records as a function of environmental variables.

Further in discussion with BiaB v2.0 we'll want a method to generate a "priority" raster, probably something like 

```
prioritymap = priority(filter)
heatmap(prioritymap) 
```

where `priority` would be a function that runs `monitoringsites` many times and records how many times an optimal sampling location is found in each cell in the raster.
