### ISSUE TITLE
Overload \circ

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/BiodiversityObservationNetworks.jl#9]
Hear me out: `(BalancedAcceptance(numpoints=100)∘AdaptiveSpatial(numpoints=10))(X)`

This specifies a complete pipeline for a matrix of entropy, and it's probably the most concise notation we can think of.

**Comment by gottacatchenall** [comment]
Yeah that sounds good--- perhaps we should have a named function, `chain` or something, such that 

`X |> chain(BalancedAcceptance(numpoints=100), AdaptiveSpatial(numpoints=10))` 

is equivalent to both the `\circ` line in your post above and the result from

`X |> BalancedAcceptance(numpoints=100) |> AdaptiveSpatial(numpoints=10))`

**Comment by tpoisot** [comment]
If we write `∘` in a smart way, `chain` is just `∘(...)` anyways -- but it makes sense, and I like the consistency with *Flux*.
